config/routes.rb
Collectors::Application.routes.draw do
  resources :eac_people, path: 'people'

  root 'welcome#index'

end

app/models/eac_name.rb
class EacName < ActiveRecord::Base
  validates_presence_of :text
  belongs_to :eac_person
end

app/models/eac_person.rb
class EacPerson < ActiveRecord::Base
  validates_presence_of :archival_record_identifier
  has_many :names, class_name: EacName
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/eac_people_controller.rb
class EacPeopleController < ApplicationController
  def index
    @eac_people = EacPerson.includes(:names).all
  end

  def show
    @eac_person = EacPerson.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/eac_people/index.html.erb
<h1>People</h1>

<ul>
  <% @eac_people.each do |person| %>
  <li><%= link_to person.archival_record_identifier, person-%>: <%= person.names[0].text %></li>

  <% end %>
</ul>

app/views/eac_people/show.html.erb
<p><%= link_to "Back to the list of people", eac_people_path %></p>

<h1><%#= @person.emu_person.full_name %></h1>

<p>
EAC record ID: <strong><%= @eac_person.archival_record_identifier %></strong>
</p>
<strong>Also known as:</strong>
<ul>
  <% @eac_person.names.each do |name| %>
    <li><%= name.text %></li>
  <% end %>
</ul>

<%== @eac_person.biography %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Collectors</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <%= yield :head %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello People!</h1>